### ISSUE TITLE
Environment Problem

### ISSUE THREAD

**Issue by BAOSHAN0123** [hughplay/TVR#3]
Hi authors,
Thanks for initial code, I want to konw are there any strict requirements for the Python dependent environment configuration of your model?

**Comment by hughplay** [comment]
In my experience, there is no strict requirement.

I used python 3.7 and the version of packages is listed in [`src/requirements.txt`](https://github.com/hughplay/TVR/blob/master/src/requirements.txt).

**Comment by BAOSHAN0123** [comment]
Thank you very much for your reply timely.
