### ISSUE TITLE
Train&Test Problem

### ISSUE THREAD

**Issue by BAOSHAN0123** [hughplay/TVR#4]
Hi authors,
I am confused that why you use the same instruction for training and testing, like this:
```
# training
python core.py train config/event.ConcatResNet.yaml
# test only
python core.py train config/event.ConcatResNet.yaml
```
I want to kow whether it is the correct operation, and whether have the trained model for testing?

**Comment by hughplay** [comment]
Sorry, it's a mistake. It should be:

```
# training
python core.py train config/event.ConcatResNet.yaml
# test only
python core.py test config/event.ConcatResNet.yaml
```

**Comment by BAOSHAN0123** [comment]
ok, authors,
for this experiment, do you have the trained model for testing, maybe the process of training dataset is a little long.
Besides, your code have another small error in `src/core.py`, list below:
```
Line 95:
preprocess(
            args.dataroot, args.split, args.split_name, args.width,
            args.height)
```
Here requires five parameters but you just list four ones.

**Comment by hughplay** [comment]
Thanks for pointing the error out. 😀 

Sorry, we currently do not have a plan to release pre-trained weights. Actually, processing the dataset is fast and you still need the processed data to test models.

**Comment by BAOSHAN0123** [comment]
Hi authors,
I find your job is worked on single-gpu, Could I change it to **multi-gpu** to let it quickly? Because only process of train dataset have wasted much time.

**Comment by hughplay** [comment]
Of course, you can.
